"""
Input and output schemas.

Input is deliberately permissive: the service accepts the full reason-matching
result JSON from netfix-backend as-is, and the formatter turns it into
readable text for the LLM prompt.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class ExplanationRequest(BaseModel):
    """Internal request object carrying the anomaly ID and the full
    reason-matching result JSON. The formatter reads the JSON and presents
    it to the LLM as structured text."""
    model_config = ConfigDict(extra="allow")

    anomaly_id: str
    rca_result_json: dict[str, Any] = Field(default_factory=dict)


class RcaExplanationReport(BaseModel):
    """A simple report carrying the explanation generated by the model."""
    explanation: str = Field(
        description="A full professional explanation written as plain prose, grounded only in the provided evidence.",
    )
